# Server
spring.application.name=qr-attendance-backend
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/qrattendance
spring.datasource.username=qruser
spring.datasource.password=qrpassword123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/qr-attendance

#email domain
app.student-email-domain=${STUDENT_EMAIL_DOMAIN:student.etf.unibl.org}
app.employee-email-domain=${EMPLOYEE_EMAIL_DOMAIN:etf.unibl.org}

#QR
app.qr-refresh-interval=${QR_REFRESH_INTERVAL:300000}

app.attendance.threshold=${ATTENDANCE_THRESHOLD:70.0}
spring.profiles.active=dev
