server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sinisa1167/qr-attendance-config-repo.git
          search-paths:
            - backend
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main
          clone-on-start: true

eureka:
  instance:
    hostname: config-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://config-server:8888/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info